#!/bin/bash

cd `dirname $0`

rm -f kernel.img
rm -rf modules

cd linux
source ../environment-armv6

mv -v .config ..
make distclean
mv -v ../.config .

make oldconfig
make -j4
make modules_install

cp -v arch/arm/boot/zImage ../kernel.img
